//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sokoban.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sokoban.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8 9
        ///EEWWWWWE
        ///WWWEEEWE
        ///WTPBEEWE
        ///WWWEBTWE
        ///WTWWBEWE
        ///WEWETEWW
        ///WBEbBBTW
        ///WEEETEEW
        ///WWWWWWWW.
        /// </summary>
        internal static string _01 {
            get {
                return ResourceManager.GetString("_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 22 11
        ///EEEEWWWWWEEEEEEEEEEEEE
        ///EEEEWEEEWEEEEEEEEEEEEE
        ///EEEEWBEEWEEEEEEEEEEEEE
        ///EEWWWEEBWWWEEEEEEEEEEE
        ///EEWEEBEEBEWEEEEEEEEEEE
        ///WWWEWEWWWEWEEEEEWWWWWW
        ///WEEEWEWWWEWWWWWWWEETTW
        ///WEBEEBEEEEEEEEEEEEETTW
        ///WWWWWEWWWWEWPWWWWEETTW
        ///EEEEWEEEEEEWWWEEWWWWWW
        ///EEEEWWWWWWWWEEEEEEEEEE
        ///.
        /// </summary>
        internal static string _02 {
            get {
                return ResourceManager.GetString("_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14 10
        ///WWWWWWWWWWWWEE
        ///WTTEEWEEEEEWWW
        ///WTTEEWEBEEBEEW
        ///WTTEEWBWWWWEEW
        ///WTTEEEEPEWWEEW
        ///WTTEEWEWEEBEWW
        ///WWWWWWEWWBEBEW
        ///EEWEBEEBEBEBEW
        ///EEWEEEEWEEEEEW
        ///EEWWWWWWWWWWWW
        ///.
        /// </summary>
        internal static string _03 {
            get {
                return ResourceManager.GetString("_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 17 10
        ///EEEEEEEEWWWWWWWWE
        ///EEEEEEEEWEEEEEPWE
        ///EEEEEEEEWEBWBEWWE
        ///EEEEEEEEWEBEEBWEE
        ///EEEEEEEEWWBEBEWEE
        ///WWWWWWWWWEBEWEWWW
        ///WTTTTEEWWEBEEBEEW
        ///WWTTTEEEEBEEBEEEW
        ///WTTTTEEWWWWWWWWWW
        ///WWWWWWWWEEEEEEEEE
        ///.
        /// </summary>
        internal static string _04 {
            get {
                return ResourceManager.GetString("_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20 20
        ///EEEEEEEWWWWWWWWWWWWE
        ///EEEEEEEWTTTTTTTTTTWE
        ///EEEEEWWWTWTWTWTWTTWE
        ///EEEEEWEEETTTTTTTTTWE
        ///EEEEEWPEBEBEBEbTbTWE
        ///EEEEWWWWWWWEWWWWWWWE
        ///EWWWWEEEWEEEEWWEEWEE
        ///WWEEEEBEWEEEEWEBEWWE
        ///WEEWBWEWWWEWWWBEEEWW
        ///WEBEEBEBEEEWEBEBEBEW
        ///WEEWEBEWWEEEEEEEWBEW
        ///WEEEBWWWWBWWWWBWWEEW
        ///WWWWEEWWEEEWEEEEWEEW
        ///EEEWBEWWEEEWEWEBBEEW
        ///EEEWEEEWEBEWEEBEEEEW
        ///EEEWWWEWEBBEWEEBEWWW
        ///EEEEEWEWEEEEWEBEWWEE
        ///EEEEEWEWWWWWWWWEWEEE
        ///EEEEEWEEEEEEEEEEWEEE
        ///EEEEEWWWWWWWWWWWWEEE
        ///.
        /// </summary>
        internal static string _05 {
            get {
                return ResourceManager.GetString("_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 25 19
        ///EEEEEEWWWWWWEEEEEEEEEEEEE
        ///EEEWWWWWEEEWEEEEEEEEEEEEE
        ///EEEWEEEWEWEWWWWWEEEEEEEEE
        ///EEEWEBEWEEBEEEEWWWWWWEEEE
        ///EEWWBEEWWWEWWEEEEEEEWEEEE
        ///WWWEEBBEBEBEWEEWWEEEWWWWW
        ///WEEEEEEEBEEEWWWWWWEWWEEEW
        ///WEEWWWWWWWWEWEEEEWEWEEWEW
        ///WWEWWWEEEEEEWWWWEWBWEWEEW
        ///EWEWWWEWWWWEWWTTEWEEEBEWW
        ///EWEEBEEBEEWBWWTTEWBWWEEWW
        ///EWEEWEWEWEEEEETTWWEWWEBEW
        ///EWWWWEEEWEWWEWTTWEEEEBEEW
        ///EEEEWWWWWEEEEWTpWEWEWEEWW
        ///EEEEEEEEWWWWWWTTWEEEWEWWE
        ///EEEEEEEEEEEEEWTTWWWWWEEWE
        ///EEEEEEEEEEEEEWTTEEEEEEEWE
        ///EEEEEEEEEEEEEWWEEWWWEEWWE
        ///EEEEEEEEEEEEEEWWWWWWWWWEE
        ///.
        /// </summary>
        internal static string _06 {
            get {
                return ResourceManager.GetString("_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 19 15
        ///EWWWWWEEEEEEEEEEEEE
        ///EWEEEWEEEEEEEEEEEEE
        ///EWEWEWWWWWWEEEEEEEE
        ///EWEEEEEEBPWWWWWWEEE
        ///EWEBEWWBEWWWEEEWEEE
        ///EWEWWWWEBEEEEBEWEEE
        ///EWEWWWWWEWEEWBEWWWW
        ///WWEEWWWWEWWBEEEEEEW
        ///WEEBWEEBEEWEWWEWWEW
        ///WEEEEEEEEEWEWTTTWEW
        ///WWWWWWEEWWWEETTTEEW
        ///EEEEEWWWWEWEWTTTWEW
        ///EEEEEEEEEEWEWWWEWEW
        ///EEEEEEEEEEWEEEEEEEW
        ///EEEEEEEEEEWWWWWWWWW
        ///.
        /// </summary>
        internal static string _07 {
            get {
                return ResourceManager.GetString("_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 23 20
        ///EWWWWWWWWWWWWWWWWWWWWWE
        ///EWEEEWWEEWEEEWEEEWEEEWE
        ///EWEBEEEEEBEEEBEEEBEEEWW
        ///WWWWWEWEEWEEEWWWEWWBWWW
        ///WEEEWEWWBWWWWWWEEEWEEEW
        ///WEBEEEWETTTTTTWEEEWEBEW
        ///WWEWEEWETTTTTTWWWWWEEEW
        ///WWEWWWWWWWWWTTWEEEWEWWW
        ///WEEEEEEEEEEWTTWEBEEEWEE
        ///WEWWEWWWEWWWTTWWEWEEWWW
        ///WEWEEEWEEEWWTTWWEWWWEEW
        ///WEEEPEEEEEEBTTWEEEEEEEW
        ///WEWEEEWEEEWWEEWEEEWWEEW
        ///WWWWWEWWWWWWWWWWWWWWEWW
        ///WEEEEEEEEEEWEEEWEEEEBEW
        ///WEBEEWEBEBEBEEEWEWEEEEW
        ///WEWBWWEBWEEWWEWWEEEEWEW
        ///WEEBEBBEWWWWEBEEBEWEWEW
        ///WEEEEEEEEEEWEEEWEEEEEEW
        ///WWWWWWWWWWWWWWWWWWWWWWW
        ///.
        /// </summary>
        internal static string _08 {
            get {
                return ResourceManager.GetString("_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 29 20
        ///EEEEEEEEEWWWWEEEEEEEEEEEEEEEE
        ///EEEEEEEEEWEEWEEEEEEEEEEEEEEEE
        ///EEEEEEEEEWEEWWWWWWWWEEEEEEEEE
        ///EEEWWWWWWWEEWEEEEEEWEEEEEEEEE
        ///EEEWEEEWEWEWEWEWEEEWWEEEEEEEE
        ///EEEWEBEEEEEBEEWWEEBEWEEEEEEEE
        ///EEWWWEBWEWEEWEWEEEEEWWWWWWWWW
        ///EEWEEBEEWEEBWEWEBBEWEEEWEWEEW
        ///EWWEWEEEWEEEEEWWWEEEEBEWEWEEW
        ///EWEEWBEEEWEWWWEEWEEWEBBWEWEEW
        ///EWEEEEBWWEBEEWEEEWWEBEEWEWEWW
        ///WWWWBEBEWEEEEWWEEWEEEBEEEETTW
        ///WEEWEEEEWWWEWEBEBEWWWEEWWWTbW
        ///WEEEEEWWEEBBEPEEBEEEEEWWTTTTW
        ///WEEWWEEWWEEEBEEWBWEEWWTTTTbTW
        ///WWEWEEBEEWEWEBWWEEWWTTTTbTWWW
        ///WWEWWEEBEEWEBEWEEWTTTTbTWW [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _09 {
            get {
                return ResourceManager.GetString("_09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap simple_32_box {
            get {
                object obj = ResourceManager.GetObject("simple-32-box", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap simple_32_box_docked {
            get {
                object obj = ResourceManager.GetObject("simple-32-box-docked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap simple_32_dock {
            get {
                object obj = ResourceManager.GetObject("simple-32-dock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap simple_32_floor {
            get {
                object obj = ResourceManager.GetObject("simple-32-floor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap simple_32_wall {
            get {
                object obj = ResourceManager.GetObject("simple-32-wall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap simple_32_worker {
            get {
                object obj = ResourceManager.GetObject("simple-32-worker", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap simple_32_worker_docked {
            get {
                object obj = ResourceManager.GetObject("simple-32-worker-docked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
